version: "3.7"

services:
  digit-recogniser:
    container_name: my-digit-recogniser
    image: mikowhykacki/digit-recogniser:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
